#!/usr/bin/env bash
set -Eeuo pipefail

INSTALL_DIR="${AWBOTNEST_DIR:-}"
WEB_PORT="${AWBOTNEST_PORT:-}"
IMAGE="${AWBOTNEST_IMAGE:-awdress/awbotnest:latest}"

info() {
  printf '\n[AWBotNest] %s\n' "$1"
}

fail() {
  printf '\n[AWBotNest] 安装失败：%s\n' "$1" >&2
  exit 1
}

[[ "$(uname -s)" == "Linux" ]] || fail "一键安装脚本目前只支持 Linux 服务器。"
[[ "${EUID}" -eq 0 ]] || fail "请使用 sudo 运行安装命令。"

if [[ -r /dev/tty && -w /dev/tty ]]; then
  if [[ -z "${INSTALL_DIR}" ]]; then
    printf '安装位置 [/opt/AWBotNest]：' >/dev/tty
    IFS= read -r INSTALL_DIR </dev/tty || true
  fi
  if [[ -z "${WEB_PORT}" ]]; then
    printf '访问端口 [18001]：' >/dev/tty
    IFS= read -r WEB_PORT </dev/tty || true
  fi
fi

INSTALL_DIR="${INSTALL_DIR:-/opt/AWBotNest}"
WEB_PORT="${WEB_PORT:-18001}"
COMPOSE_FILE="${INSTALL_DIR}/docker-compose.yml"

[[ "${WEB_PORT}" =~ ^[0-9]+$ ]] || fail "端口必须是数字。"
(( WEB_PORT >= 1 && WEB_PORT <= 65535 )) || fail "端口必须在 1 到 65535 之间。"

if ! command -v curl >/dev/null 2>&1; then
  fail "服务器缺少 curl，请先安装 curl 后重试。"
fi

if ! command -v docker >/dev/null 2>&1; then
  info "未检测到 Docker，正在安装 Docker..."
  docker_installer="$(mktemp)"
  trap 'rm -f "${docker_installer:-}"' EXIT
  curl -fsSL https://get.docker.com -o "${docker_installer}"
  sh "${docker_installer}"
fi

if command -v systemctl >/dev/null 2>&1; then
  systemctl enable --now docker >/dev/null 2>&1 || true
fi

docker info >/dev/null 2>&1 || fail "Docker 服务没有正常运行。"
if docker compose version >/dev/null 2>&1; then
  compose=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  compose=(docker-compose)
else
  fail "未检测到 Docker Compose。"
fi

info "准备安装目录 ${INSTALL_DIR}..."
mkdir -p \
  "${INSTALL_DIR}/plugins" \
  "${INSTALL_DIR}/logs" \
  "${INSTALL_DIR}/sessions" \
  "${INSTALL_DIR}/db_file" \
  "${INSTALL_DIR}/data"

if [[ ! -f "${COMPOSE_FILE}" ]]; then
  cat >"${COMPOSE_FILE}" <<EOF
# Generated by the AWBotNest one-click installer.
services:
  awbotnest:
    image: ${IMAGE}
    container_name: AWBotNest
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "${WEB_PORT}:18001"
    volumes:
      - ./plugins:/app/plugins
      - ./logs:/app/logs
      - ./sessions:/app/sessions
      - ./db_file:/app/db_file
      - ./data:/app/data
EOF
else
  info "检测到已有配置，将保留 ${COMPOSE_FILE}。"
fi

info "正在拉取最新镜像并启动平台..."
"${compose[@]}" -f "${COMPOSE_FILE}" pull
"${compose[@]}" -f "${COMPOSE_FILE}" up -d --remove-orphans

server_ip=""
if command -v hostname >/dev/null 2>&1 && command -v awk >/dev/null 2>&1; then
  server_ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
fi
server_ip="${server_ip:-服务器IP}"

printf '\nAWBotNest 已启动。\n'
printf '访问地址：http://%s:%s\n' "${server_ip}" "${WEB_PORT}"
printf '安装目录：%s\n' "${INSTALL_DIR}"
printf '默认账号：admin\n'
printf '默认密码：password（登录后请立即修改）\n\n'
