#!/usr/bin/env bash
set -Eeuo pipefail

INSTALL_DIR="${AWBOTNEST_DIR:-}"
DEPLOY_MODE="${AWBOTNEST_MODE:-}"
WEB_PORT="${AWBOTNEST_PORT:-}"
PLATFORM_PORT="${AWBOTNEST_PLATFORM_PORT:-}"
IMAGE="${AWBOTNEST_IMAGE:-awdress/awbotnest_v2:latest}"

info() { printf '\n[AWBotNest] %s\n' "$1"; }
fail() { printf '\n[AWBotNest] 安装失败：%s\n' "$1" >&2; exit 1; }

compose_tmp=""
docker_installer=""
cleanup() {
  [[ -z "${compose_tmp}" ]] || rm -f -- "${compose_tmp}"
  [[ -z "${docker_installer}" ]] || rm -f -- "${docker_installer}"
  return 0
}
trap cleanup EXIT

[[ "$(uname -s)" == "Linux" ]] || fail "一键安装脚本目前只支持 Linux 服务器。"
[[ "${EUID}" -eq 0 ]] || fail "请使用 sudo 运行安装命令。"

if [[ -r /dev/tty && -w /dev/tty ]]; then
  if [[ -z "${INSTALL_DIR}" ]]; then
    printf '安装位置 [/opt/AWBotNest]：' >/dev/tty
    IFS= read -r INSTALL_DIR </dev/tty || true
  fi
  if [[ -z "${DEPLOY_MODE}" ]]; then
    printf '网络模式 [bridge/host，默认 bridge]：' >/dev/tty
    IFS= read -r DEPLOY_MODE </dev/tty || true
  fi
  if [[ -z "${WEB_PORT}" && "${DEPLOY_MODE,,}" != "host" ]]; then
    printf '访问端口（bridge 映射端口） [18001]：' >/dev/tty
    IFS= read -r WEB_PORT </dev/tty || true
  fi
  if [[ -z "${PLATFORM_PORT}" ]]; then
    printf '平台监听端口（host 模式必填，默认 18001） [18001]：' >/dev/tty
    IFS= read -r PLATFORM_PORT </dev/tty || true
  fi
fi

INSTALL_DIR="${INSTALL_DIR:-/opt/AWBotNest}"
DEPLOY_MODE="${DEPLOY_MODE:-bridge}"
WEB_PORT="${WEB_PORT:-18001}"
PLATFORM_PORT="${PLATFORM_PORT:-18001}"
COMPOSE_FILE="${INSTALL_DIR}/docker-compose.yml"
RUNTIME_OVERRIDE="${INSTALL_DIR}/docker-compose.awbotnest-runtime.yml"

case "${DEPLOY_MODE,,}" in
  bridge|host) DEPLOY_MODE="${DEPLOY_MODE,,}" ;;
  *) fail "网络模式只能是 bridge 或 host。" ;;
esac

validate_port() {
  local name="$1" value="$2"
  [[ "${value}" =~ ^[0-9]+$ ]] || fail "${name}必须是数字。"
  (( ${#value} <= 5 )) || fail "${name}必须在 1 到 65535 之间。"
  value=$((10#${value}))
  (( value >= 1 && value <= 65535 )) || fail "${name}必须在 1 到 65535 之间。"
  printf '%s' "${value}"
}

WEB_PORT="$(validate_port '访问端口' "${WEB_PORT}")"
PLATFORM_PORT="$(validate_port '平台监听端口' "${PLATFORM_PORT}")"
if [[ "${DEPLOY_MODE}" == "host" ]]; then
  # Host network has no published-port mapping; the app listens directly on
  # the selected platform port on the host.
  WEB_PORT="${PLATFORM_PORT}"
fi
command -v curl >/dev/null 2>&1 || fail "服务器缺少 curl，请先安装 curl 后重试。"

if ! command -v docker >/dev/null 2>&1; then
  info "未检测到 Docker，正在安装 Docker..."
  docker_installer="$(mktemp)"
  curl -fsSL https://get.docker.com -o "${docker_installer}"
  sh "${docker_installer}"
fi

if command -v systemctl >/dev/null 2>&1; then
  systemctl enable --now docker >/dev/null 2>&1 || true
fi
docker info >/dev/null 2>&1 || fail "Docker 服务没有正常运行。"

if docker compose version >/dev/null 2>&1; then
  compose=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  compose=(docker-compose)
else
  fail "未检测到 Docker Compose。"
fi

info "准备安装目录 ${INSTALL_DIR}..."
mkdir -p "${INSTALL_DIR}/plugins" "${INSTALL_DIR}/sessions" "${INSTALL_DIR}/data"

compose_files=(-f "${COMPOSE_FILE}")

write_generated_compose() {
  if [[ "${DEPLOY_MODE}" == "host" ]]; then
    cat >"${COMPOSE_FILE}" <<EOF
# Generated by the AWBotNest one-click installer.
services:
  awbotnest:
    image: ${IMAGE}
    container_name: AWBotNest_V2
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - AWBOTNEST_WEB_PORT=${PLATFORM_PORT}
    healthcheck:
      test: ["CMD", "python", "-c", "import os, urllib.request; urllib.request.urlopen('http://127.0.0.1:' + os.getenv('AWBOTNEST_WEB_PORT', '18001') + '/api/health', timeout=3)"]
      interval: 30s
      timeout: 5s
      start_period: 20s
      retries: 3
    volumes:
      - ./plugins:/app/plugins
      - ./sessions:/app/sessions
      - ./data:/app/data
EOF
  else
    cat >"${COMPOSE_FILE}" <<EOF
# Generated by the AWBotNest one-click installer.
services:
  awbotnest:
    image: ${IMAGE}
    container_name: AWBotNest_V2
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - AWBOTNEST_WEB_PORT=${PLATFORM_PORT}
    ports:
      - "${WEB_PORT}:${PLATFORM_PORT}"
    healthcheck:
      test: ["CMD", "python", "-c", "import os, urllib.request; urllib.request.urlopen('http://127.0.0.1:' + os.getenv('AWBOTNEST_WEB_PORT', '18001') + '/api/health', timeout=3)"]
      interval: 30s
      timeout: 5s
      start_period: 20s
      retries: 3
    volumes:
      - ./plugins:/app/plugins
      - ./sessions:/app/sessions
      - ./data:/app/data
EOF
  fi
}

if [[ ! -f "${COMPOSE_FILE}" ]]; then
  write_generated_compose
else
  [[ ! -L "${COMPOSE_FILE}" ]] || fail "配置是符号链接，请手动修改端口，避免覆盖链接。"
  if [[ "$(sed -n '1p' "${COMPOSE_FILE}")" == "# Generated by the AWBotNest one-click installer." ]]; then
    compose_backup="$(mktemp "${COMPOSE_FILE}.bak.XXXXXX")"
    cp -p -- "${COMPOSE_FILE}" "${compose_backup}"
    write_generated_compose
    info "已按 ${DEPLOY_MODE} 模式更新安装器配置。原配置备份：${compose_backup}"
  else
    # Do not rewrite a user-maintained Compose file.  Apply the selected
    # network/port policy through a separate override that survives upgrades.
    cat >"${RUNTIME_OVERRIDE}" <<EOF
# Generated by the AWBotNest one-click installer. Do not edit the base file.
services:
  awbotnest:
    environment:
      TZ: Asia/Shanghai
      AWBOTNEST_WEB_PORT: "${PLATFORM_PORT}"
EOF
    if [[ "${DEPLOY_MODE}" == "host" ]]; then
      cat >>"${RUNTIME_OVERRIDE}" <<'EOF'
    network_mode: host
    ports: []
EOF
    else
      cat >>"${RUNTIME_OVERRIDE}" <<EOF
    network_mode: bridge
    ports:
      - "${WEB_PORT}:${PLATFORM_PORT}"
EOF
    fi
    compose_files+=( -f "${RUNTIME_OVERRIDE}" )
    info "检测到自定义 Compose，已生成运行模式覆盖文件：${RUNTIME_OVERRIDE}"
  fi
fi

"${compose[@]}" "${compose_files[@]}" config -q || fail "Compose 配置校验失败，请检查网络模式和端口设置。"

info "正在拉取最新镜像并启动 AWBotNest..."
"${compose[@]}" "${compose_files[@]}" pull awbotnest
"${compose[@]}" "${compose_files[@]}" up -d awbotnest

server_ip=""
if command -v hostname >/dev/null 2>&1 && command -v awk >/dev/null 2>&1; then
  server_ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
fi
server_ip="${server_ip:-服务器IP}"

printf '\nAWBotNest 已启动。\n'
printf '网络模式：%s\n' "${DEPLOY_MODE}"
printf '访问地址：http://%s:%s\n' "${server_ip}" "${PLATFORM_PORT}"
if [[ "${DEPLOY_MODE}" == "bridge" && "${WEB_PORT}" != "${PLATFORM_PORT}" ]]; then
  printf '宿主映射端口：%s（容器平台端口：%s）\n' "${WEB_PORT}" "${PLATFORM_PORT}"
fi
printf '安装目录：%s\n' "${INSTALL_DIR}"
printf '首次打开网页后，请按页面提示设置管理员用户名和密码。\n\n'
